In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'C:\\Users\\JOEL\\anaconda3\\envs\\ml-zoomcamp\\lib\\site-packages\\numpy\\__init__.py'>

# Creating a Numpy Array

In [3]:
# creating a numpy array
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
a = np.array([1,2,4,6,9,20])

In [8]:
a[2]

4

In [9]:
a[2] = 10
a

array([ 1,  2, 10,  6,  9, 20])

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.linspace(0,100,11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Multi-Dimensional Arrays

In [15]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
n = np.array([
[1,2,3],
[4,5,6],
[7,8,9]])

In [20]:
n[0,1] = 20

In [21]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [22]:
n[0]

array([ 1, 20,  3])

In [23]:
n[1]

array([4, 5, 6])

In [24]:
n[2]

array([7, 8, 9])

In [25]:
n[2] = [10,19,20]

In [26]:
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [10, 19, 20]])

In [27]:
n[:,1]

array([20,  5, 19])

In [28]:
n[:,1] = [1,2,3]

In [29]:
n

array([[ 1,  1,  3],
       [ 4,  2,  6],
       [10,  3, 20]])

# Randomly Generated Arrays

In [36]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [35]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [38]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element wise Operations

In [39]:
a = np.arange(5)

In [40]:
a + 1

array([1, 2, 3, 4, 5])

In [41]:
a * 2

array([0, 2, 4, 6, 8])

In [42]:
b = ((10 + (a * 2)) **2)/100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [43]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [44]:
a * b

array([ 0.  ,  1.44,  3.92,  7.68, 12.96])

# Comparison Operations

In [45]:
a

array([0, 1, 2, 3, 4])

In [46]:
a>=2

array([False, False,  True,  True,  True])

In [47]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [48]:
a>b

array([False, False,  True,  True,  True])

In [49]:
# which elements of a are greater than b
a[a>b]

array([2, 3, 4])

# Summarizing operations

In [50]:
a

array([0, 1, 2, 3, 4])

In [51]:
a.min()

0

In [52]:
a.max()

4

In [53]:
a.sum()

10

In [54]:
a.mean()

2.0

In [55]:
a.std()

1.4142135623730951

In [56]:
n

array([[ 1,  1,  3],
       [ 4,  2,  6],
       [10,  3, 20]])

In [57]:
n.sum()

50

In [58]:
n.min()

1

In [59]:
n.std()

5.756370598661609

In [60]:
n.max()

20