# Linear Algebra Refresher.

In [1]:
import numpy as np

## Vector Operations

In [2]:
u = np.array([2,4,5,6,9])
u

array([2, 4, 5, 6, 9])

In [3]:
v = np.array([3,5,7,9,2])
v

array([3, 5, 7, 9, 2])

In [4]:
u + v

array([ 5,  9, 12, 15, 11])

### Vector-vector multiplication (Dot product)

In [5]:
u.shape

(5,)

In [6]:
v.shape

(5,)

In [7]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [8]:
vector_vector_multiplication(u=u, v=v)

133.0

In [10]:
u.dot(v)

133

### Matrix-Vector Multiplication

In [11]:
U = np.array([
    [2,3,4,5],
    [1,3,6,9],
    [7,4,9,3],
    [3,2,10,4]
])

In [13]:
U

array([[ 2,  3,  4,  5],
       [ 1,  3,  6,  9],
       [ 7,  4,  9,  3],
       [ 3,  2, 10,  4]])

In [17]:
U.shape

(4, 4)

In [14]:
v = np.array([1,1.5,6,7])

In [15]:
v

array([1. , 1.5, 6. , 7. ])

In [18]:
v.shape

(4,)

In [19]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    n = U.shape[0]
    result = np.zeros(n)
    for i in range(n):
        result[i] = vector_vector_multiplication(U[i], v)
    return result

In [20]:
matrix_vector_multiplication(U,v)

array([ 65.5, 104.5,  88. ,  94. ])

In [21]:
U.dot(v)

array([ 65.5, 104.5,  88. ,  94. ])

### Matrix-matrix multiplication

In [28]:
V = np.array([
    [2, 1.5, 3, 6],
    [3, 7, 9, 5],
    [1, 9, 5, 10],
    [9,8,5,8]
])

In [32]:
def matrix_matrix_multiplication(U,V):
    assert U.shape[1] == V.shape[0]
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = U[:,i]
        Uvi = matrix_vector_multiplication(U,vi)
        result[:,i] = Uvi
    return result
        

In [33]:
matrix_matrix_multiplication(U,V)

array([[ 50.,  41., 112.,  69.],
       [ 74.,  54., 166.,  86.],
       [ 90.,  75., 163., 110.],
       [ 90.,  63., 154.,  79.]])

In [34]:
U.dot(V)

array([[ 62. , 100. ,  78. , 107. ],
       [ 98. , 148.5, 105. , 153. ],
       [ 62. , 143.5, 117. , 176. ],
       [ 58. , 140.5,  97. , 160. ]])

### Identity Matrix

In [35]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [40]:
I = np.eye(4)

In [41]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
V

array([[ 2. ,  1.5,  3. ,  6. ],
       [ 3. ,  7. ,  9. ,  5. ],
       [ 1. ,  9. ,  5. , 10. ],
       [ 9. ,  8. ,  5. ,  8. ]])

In [43]:
V.dot(I)

array([[ 2. ,  1.5,  3. ,  6. ],
       [ 3. ,  7. ,  9. ,  5. ],
       [ 1. ,  9. ,  5. , 10. ],
       [ 9. ,  8. ,  5. ,  8. ]])

### Inverse

In [48]:
V = np.array([
    [1, 2, 3],
    [2, 6, 8],
    [9,6,1]
])

In [49]:
V_inverse = np.linalg.inv(V)

In [50]:
V_inverse

array([[ 1.5       , -0.57142857,  0.07142857],
       [-2.5       ,  0.92857143,  0.07142857],
       [ 1.5       , -0.42857143, -0.07142857]])

In [52]:
V_inverse.dot(V)

array([[ 1.00000000e+00,  4.44089210e-16,  1.11022302e-15],
       [-4.16333634e-17,  1.00000000e+00,  2.91433544e-16],
       [ 5.55111512e-17, -3.33066907e-16,  1.00000000e+00]])